#!/usr/local/bin/python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibnext(n_2, n_1):
    return n_2 + n_1

def makeEvenFibs(fmax):
    n_2 = 0
    n_1 = 1
    result = 0
    while n_1 < fmax:
        n = fibnext(n_2, n_1)
        n_2 = n_1
        n_1 = n
        if (n & 1) == 0:    #n is even
            result += n

    return result


def main():
    #print("Hello World!")
    print(makeEvenFibs(4000000))


main()



