#!/usr/local/bin/python

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
  3: 1,3
   6: 1,2,3,6
   10: 1,2,5,10
   15: 1,3,5,15
   21: 1,3,7,21
   28: 1,2,4,7,14,28
   We can see that 28 is the first triangle number to have over five divisors.

   What is the value of the first triangle number to have over five hundred divisors?
"""

from primes import PrimeGenerators, PrimeMethods
import math

def triangle_number_gen():
    i = 0
    t = 0
    while True:
        i += 1
        t += i
        yield t

def problem12(n):
    i = 0
    for t in triangle_number_gen():
        i += 1
        factors = PrimeMethods.get_prime_factors(t)
        n_divisors = PrimeMethods.n_factors(factors)
        if n_divisors > n:
            return t

def problem12_v2(n):
    i = 2
    counts = [0, 0, 1]
    while True:
        t = i * (i + 1) / 2
        counts.append(PrimeMethods.n_divisors(i + 1))
        n_factors = None
        if (i & 1) == 0:
            n_factors = counts[i / 2] * counts[i + 1]
        else:
            n_factors = counts[(i + 1) / 2] * counts[i]

        if n_factors > n:
            return t

        i += 1



def main():
    #print("Hello World!")
    print(problem12_v2(500))


main()



